### ISSUE TITLE
модуль ORM при попытке чтения поля bindings возвращает строку, равную идентификатору, а не коллекцию

### ISSUE THREAD

**Issue by Ole-x** [Eresus/ORM#7]
Имеем: 

class Works_Entity_Table_Project extends Orm_Table
{
  public function setTableDefinition()
    {
    'id' => array(
      'type' => 'integer',
      'unsigned' => true,
      'autoincrement' => true,
      ),
      ................
    'products' => array(
      'type' => 'bindings',
      'class' => 'Works_Entity_Product', ...

и, соответственно:
class Works_Entity_Table_Product extends ORM_Table
{
  public function setTableDefinition()
    {
      $this->setTableName('works_products');
      $this->hasColumns(array(
        'id' => array(
        'type' => 'integer',
        'unsigned' => true,
        'autoincrement' => true, ...

В результате в БД есть три таблицы: works_projects, works_products и works_projects_products

Условия:

В БД есть запись, где works_projects.id = 2
В БД есть запись, где works_products.id = 2

Если их попытаться связать, то плагин ORM начинает глючить:
Когда в таблице works_projects_products появляется запись, где projects == products, т.е. идентификатор объекта Works_Entity_Project равен идентификатору Works_Entity_Product - модуль ORM при попытке чтения возвращает строку, равную этому идентификатору, а не коллекцию. Независимо от наличия остальных записей.

При попытке создания такой связи, модуль возврашает ошибку о неуникальности записи

**Comment by mekras** [comment]
Попробуй последнюю версию из develop. Я там исправил ошибку, связанную с конструктором ORM_Entity, которая давала похожий результат.

**Comment by Ole-x** [comment]
Почти заработало.
Увидел, что теперь в свойство с 'type' => 'bindings' нужно передавать не массив идентификаторов связанных объектов, а массив связанных объектов.

Но теперь появилась другая проблема с ID
Если в массиве связанных объектов будет ОДИН объект, у которого идентификатор равен идентификатору "родителя", то изменения в связи просто не внесутся. 
Если в массиве связанных объектов будет НЕСКОЛЬКО объектов, у одного из которых идентификатор равен идентификатору "родителя", то будет ошибка:
Database query failed
SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '7-4' for key 'PRIMARY': INSERT INTO works_projects_products ( projects, products ) VALUES ( '7', '4' )
см. пример: http://dvaslona.ru.test.dvaslona.com/admin.php?mod=content&section=4&id=7&id=7&action=edit
пробуем привязать Продукты - "переделка сайтов"

**Comment by mekras** [comment]
И раньше **надо** было передавать список объектов, но **можно** было и идентификаторов. Второй вариант пришлось убрать.

**Comment by Ole-x** [comment]
Ничего не имею против :)
"Идентификаторов" конечно выглядит проще, но "объектов" - логичнее.

**Comment by Ole-x** [comment]
Да, теперь ошибки нет.
